### ISSUE TITLE
Release 7.0.1 of macros to crates.io?

### ISSUE THREAD

**Issue by drager** [paritytech/jsonrpc#180]
Hey, shouldn't the `jsonrpc-macros` crate be release to crates.io? https://github.com/paritytech/jsonrpc/tree/master/macros

**Comment by tomusdrw** [comment]
Indeed it should, although `jsonrpc-macros` now has a dependency on `jsonrpc-pubsub` which in turn requires `jsonrpc-ws-server` and `jsonrpc-ipc-server` both of them being not publishable due to git dependencies they require.

The issue is logged here: #112 

I will try to prepare a PR to remove those dev-depdencies and release both `jsonrpc-macros` and `jsonrpc-pubsub` today.

**Comment by drager** [comment]
I see, sounds great. Thank you!
