### ISSUE TITLE
Recommended architecture for JSON-RPC via TCP server

### ISSUE THREAD

**Issue by adam0z** [paritytech/jsonrpc#191]
Could you tell me if my idea make sense?

I'm writing a search backend in Rust as a separate library. I'm going to use your _jsonrpc_ library for TCP Server, more precisely` jsonrpc_tcp_server::{ServerBuilder};`

Then, I will add each my public function as async method like [record_pending](https://github.com/paritytech/jsonrpc/blob/bb77cd40f2f8da32392e5ab788fd1a2ce70b51ba/ws/src/tests.rs#L76) in tests (but using `extend_with` my trait).
Thanks to that my server would be async and would create a separate thread for each request.

Then, I will use nginx or some load balancer to distribute traffic across multiple instance of my server. Do you have any preferred solution for this?

Does it make sense to add async methods instead of sync ones? Can I limit number of threads?

Thanks for answers

**Comment by tomusdrw** [comment]
Spawning a thread for each request is most likely not a good approach.
The whole architecture of this library is based on [`futures`](https://docs.rs/crate/futures), which allows you to handle efficiently multiple requests at the same time using just a single thread (event loop).
If you really need threads in your app, take a look at [`futures_cpupool`](https://docs.rs/crate/futures-cpupool/0.1.5). It will create a pool of threads that the requests will share and each request will be dispatched to one of the threads.

For simplicity you can also use sync methods everywhere and implement a thread pool as a `jsonrpc_core::Middleware`. For an example have a look here:
https://github.com/paritytech/parity/blob/f3e7d7c725fcd39040d41d2dee231050342f60c0/rpc/src/v1/informant.rs#L232
each request goes through the middleware and you can then dispatch it on the cpupool. It's possible because sync method calls are wrapped in `futures::lazy` - so they don't get invoked right away when calling `process()`.

Regarding the load balancing - if you don't need persistent connections (or a pub/sub feature) and you don't have in-memory state it might be better to just use `http` transport - this will cause much less load on the server because the connections will be established only if the requests are coming and it will also allow you to do better load balancing since two requests from a particular client can be routed to different servers and processed in parallel.

**Comment by adam0z** [comment]
Thanks for the answer.
By default all added async methods are handled using futures and just a single thread?
So, is it a proper implementation of async sleep?
```rust
fn async_sleep(&self, millis: u64) -> BoxFuture<String, Error> {
  Timer::default().sleep(time::Duration::from_millis(millis)).then(
    |_| {
      Ok("Wake up!".into())
    }
  }).boxed()
}
```

And by default only one thread would be used - to use more must I use `futures_cpupool`?

Regarding the load balancing, using TCP, wouldn't the connections be established one per request when it came? Why two requests from a particular client could not by routed to different servers using TCP?

**Comment by tomusdrw** [comment]
The code looks ok - note that the fact that it sleeps doesn't block processing other requests.
Yes, `cpupool` is used to run heavy/non-async tasks outside of the event loop.

You can send many requests over a single TCP connection - no need to re-connect after each request. I'm not really aware how TCP load balancing in nginx works, so can't help with that one.
