### ISSUE TITLE
Implement Error for core::Error

### ISSUE THREAD

**Issue by ivanovaleksey** [paritytech/jsonrpc#253]
Hello,

while migrating an application from `error-chain` to `failure` I noticed that `core::Error` doesn't implement `Error`.
I can't define return type as `Result<T, failure::Error>` because of that.

I would like to know are there any problems which block us from this implementation?
If this could be done I would like to try to work on it.

Thanks.

P.S.
I also asked on [forum](https://users.rust-lang.org/t/migrate-application-from-error-chain-to-failure/16601) if I work with errors right.
Maybe I just miss something.
Also I am not sure if implementing `Error` would be useful at all.

**Comment by tomusdrw** [comment]
We have discussed it here https://github.com/paritytech/jsonrpc/issues/240#issuecomment-367293733

I'm still not sure what would be the right way to approach it. I don't see why `core::Error` would ever be wrapped in some another error type, since it's a serializable response that should be sent to the client.

That said I can see how this could help writing client libraries, so let's implement it.

**Comment by ivanovaleksey** [comment]
@tomusdrw oh, sorry, I totally forgot about #240 (thought it's my issue too). 🤦‍♂️ 

Yesterday I was stumbling upon that error management story. Once I opened this issue I did realize that there was no any reason for wrapping `core::Error` because it's just return type of RPC methods. One only need to provide `impl From<MyError> for core::Error`.

Taking my ignorance into account do you still think it would be useful to implement `Error`?

**Comment by tomusdrw** [comment]
Yes, I think that feature would be useful for creating client libraries using `core`, so let's implement it.

**Comment by adam0z** [comment]
+1 This would be nice a feature.

**Comment by ivanovaleksey** [comment]
Hi, I will try to make it this days.
@adam0z glad it would be useful for you.
