### ISSUE TITLE
Add Example for request params 

### ISSUE THREAD

**Issue by hskang9** [paritytech/jsonrpc#378]
Example for handling params from request is missing. 

I discovered jsonrpc uses `parse` and method to parse Params struct.

Is parsing request parameters in progress?

**Comment by mycognosist** [comment]
@hskang9 

`jsonrpc_core::types::params::Params` implements the `serde::de::Deserialize` trait ([docs](https://docs.rs/serde/1.0.87/serde/de/trait.Deserialize.html)). This allows request parameters to be parsed into a `struct`. An example:

`Cargo.toml`

```
[dependencies]
jsonrpc-http-server = "10.0"
serde = { version = "1.0.87", features = ["derive"] }
```

`main.rs`

```
use jsonrpc_http_server::*;
use jsonrpc_http_server::jsonrpc_core::*;
use serde::Deserialize;

#[derive(Deserialize, Debug)]
pub struct Person {
    name: String,
    age: u32,
}

fn main() {
    let mut io = IoHandler::default();
    io.add_method("say_hello", |params: Params| {
        let person : Person = params.parse().unwrap();
        // parameters can now be accessed as person.name & person.age        
        Ok(Value::String("hello".into()))
    });

    let server = ServerBuilder::new(io)
        .cors(DomainsValidation::AllowOnly(vec![AccessControlAllowOrigin::Null]))
        .start_http(&"127.0.0.1:3030".parse().unwrap())
        .expect("Unable to start RPC server");

    server.wait();
}
```
Request example:

`curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "say_hello", "params" : {"name": Alice, "age": 37}, "id":1 }' 127.0.0.1:3030`

I hope that is helpful to you! I only just learned how to do this myself, so the example may not be 100% idiomatic but it does work.

Note: You may want to handle the `Result` type return by `parse()`, rather than simply calling `unwrap()` as I have done in the example.

**Comment by mycognosist** [comment]
@hskang9 I just noticed your pull request, my apologies for the unnecessary post.

**Comment by hskang9** [comment]
@mycognosist It is okay, your code looks great! I think you can add this in http examples. but there is already serde_derive package in the project dependancy so you just need to code `use serde_derive::{Deserialize}` in the example.
