### ISSUE TITLE
JSON Neo Tokio 0.2

### ISSUE THREAD

**Issue by workingjubilee** [paritytech/jsonrpc#582]
tokio 0.2 has a lot of pertinent updates for IPC. #485 appears to still be in-progress which is obviously blocking, but it would be good to know if there are any additional requirements beyond that before jsonrpc-* can move to a ^0.2 version of tokio. Feel free to close this issue if the answer is "The moment #485 closes, tokio 0.2 is also ready" or "No plans to make that available, please move to jsonrpsee."

**Comment by tomusdrw** [comment]
I don't see any obstacles to tokio-0.2 migration, I was considering it would be part of #485. That said, we don't currently have anyone actively working on migrating the transports due to lack of time. The `jsonrpc` vs `jsonrpsee` decision is yet to be made as well, so I unfortunately can't commit to anything. However `jsonrpc`, is a community project and I really hope that it can transcend paritytech's use of it.
