### ISSUE TITLE
how to create new handler when new connection income

### ISSUE THREAD

**Issue by ahczbhht1989** [paritytech/jsonrpc#648]
When I create a jsonrpc server on websocket channel, code as below
```rust
    let r = XXX::new();
    io.extend_with(r.to_delegate());
    let server = ServerBuilder::with_meta_extractor(io, |context: &RequestContext| {
        Arc::new(Session::new(context.sender()))
    })
```
and I have state in my handler,I want to have different state with different client（each client have it's own handler）.
The reason is code 
```rust
// pass the io object to ServerBuilder
let server = ServerBuilder::with_meta_extractor(io, |context: &RequestContext| {
        Arc::new(Session::new(context.sender()))
    })

```
But I find when connect to server from different client, the state is current state in my XXX
So How can I handle this.

**Comment by tomusdrw** [comment]
Please take a look at the [`PubSubMetadata` trait](https://docs.rs/jsonrpc-pubsub/18.0.0/jsonrpc_pubsub/trait.PubSubMetadata.html).

You need to either customize the `Metadata` (instead of using the default `Arc<Session>`) and there you can hold any per-user data (make sure to implement correct `Drop`), or you need to associate some id to every user and then store the per-user data externally.
